apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: circle-api
  template:
    metadata:
      labels:
        app: circle-api
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
