apiVersion: v1
kind: Service
metadata:
  name: circle-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: circle-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
